/**
 * !! DO NOT EDIT THIS FILE MANUALLY !!
 * このコードは scripts/make-sdk/index.js によって自動生成されています。
 */

import * as API from 'aws-amplify/api';

/**
 * ユーザー情報
 * @param {null} _ - 未使用
 * @param {Auth} auth - 認証情報
 * @returns {Auth} 認証情報
 */
export async function user(input) {
	const {body} = await API.post({
		apiName: 'AuthApi',
		path: '/user',
		options: {
			body: input,
		},
	}).response;
	return body.json();
}
