/**
 * !! DO NOT EDIT THIS FILE MANUALLY !!
 * このコードは scripts/make-sdk/index.js によって自動生成されています。
 */

import * as API from 'aws-amplify/api';

/**
 * [確認用] エラーを返します
 */
export async function error403(input) {
	const {body} = await API.post({
		apiName: 'UnauthApi',
		path: '/error403',
		options: {
			body: input,
		},
	}).response;
	return body.json();
}
